### ISSUE TITLE
Opt for single quotes rather than double quotes

### ISSUE THREAD

**Issue by nguyenj** [polleverywhere/js-config#6]
Is there a reason to continue with double quotes when we have template literals? We hardly need any string escaping and if we do for these special cases, double quotes are fine; but it shouldn’t be the default requirement. 

That extra shift key is a PITA.

**Comment by thoughtless** [comment]
IIRC the decision to use `"` rather than `'` was to make searching for strings easier. You could reliably search for `"` rather than `'`. I'm not sure about now, but when I did more CoffeeScript we did enough interpolation with `"#{}"` that this mattered.

We will likely keep this convention on the server side, but I don't really have a strong opinion on the client side. Doing it around the same time as a switch to ES6 makes sense to me.

**Comment by nguyenj** [comment]
Yeah I know the backstory; but moving forward, I'm suggesting to move off of double quotes as the standard (for JS).

For ES6 string interpolation, ES6 gave use [template literals ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

**Comment by adam-h** [comment]
I'm not averse to this, as long as all the repos are also updated to follow this pattern (eslint can auto-fix it for us).

I shot this down in the past mainly as only the rule was updated, and none of the code - don't want that to happen again.

My habit is to always type `"`, but I can adapt :)

**Comment by dannobytes** [comment]
I am 100% on board for single quotes. I really dislike doubles within JS in particular.

There was a time long ago when I was using doubles, but I recall the adaptation to single quotes was quite easy.

I'm fully onboard to move us as close (if not all the way) to full StandardJS's spec. And as @adam-h  mentioned, auto-fix would make this particular change easy.
